### PR TITLE
Fixed path

### PR DESCRIPTION
**Pull request by fgimenez**

### CODE REVIEW

**Comment by elopio** [comment]
This soon will be credentials for scalingstack, so maybe we can call the directory .openstack instead of .canonistack.
That would require to update the jobs, so feel free to ignore this or do it in a different PR.

thanks.

**Comment by fgimenez** [comment]
Thanks Leo, I've taken the opportunity to update all the paths and job names. The only canonistack reference still there is the one used for determining the instance ip, I'll update that when we switch the provider

**Comment by fgimenez** [comment]
@elopio please take a look at #11, it's what we were talking about yesterday, this way we can have the job's config in a single place and have this project in sync with that. 

Let me know what do you think, if we could move there the required plugins it would be great. If it looks good to you we can close this PR.

**Comment by fgimenez** [comment]
@elopio the new jobs directory layout is taken into acount in #12, closing this one

**Pull request closed without merging**
